#!/usr/bin/env node

var demos = {};

global.util = require('util');
global.define = function (name, func) {
  demos[name] = func;
};

require('./lib');

var demoName = process.argv[2];

if (demoName === undefined) {
  sys.puts("A demo to run must be specified.");
  process.exit(1);
} else if (demos[demoName] === undefined) {
  sys.puts("Demo " + demoName + " is not defined.");
  process.exit(1);
} else {
  console.log("\n\033[32mEXAMPLE\033[0m \033[35m" + demoName + "\033[0m");
  demos[demoName].apply(null, process.argv.slice(3));
  console.log("");
}

