#!/usr/bin/env node

global.util = require('util');

var demos = {};

global.define = function (name, func) {
  if (demos[name]) {
    whoops("Demo " + name + " cannot be defined");
  } else {
    demos[name] = func;
  }
};

function pcolor(id, msg) { return "\033[" + id + "m" + msg + "\033[0m"; }
global.red    = function (msg) { return pcolor(31, msg); };
global.green  = function (msg) { return pcolor(32, msg); };
global.purple = function (msg) { return pcolor(35, msg); };
global.cyan   = function (msg) { return pcolor(36, msg); };

function whoops(msg) {
  util.puts(red("! \033[31m" + msg + "\033[0m"));
}

function info(label, msg) {
  util.puts("\n" + green(label) + " " + purple(msg));
}

require('./lib');

var demoName = process.argv[2],
    demo = demos[demoName];
if (!demo) {
  whoops("A demo to run must be specified.\n");
  for (var demo in demos) { util.puts("- " + demo); }
} else {
  info("EXAMPLE", demoName);
  demos[demoName].apply(null, process.argv.slice(3));
}
console.log("");

